---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - elastic.co.elastic
  resources:
  - kibanas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elastic.co.elastic
  resources:
  - kibanas/finalizers
  verbs:
  - update
- apiGroups:
  - elastic.co.elastic
  resources:
  - kibanas/status
  verbs:
  - get
  - patch
  - update
